:access_key:                            1235125ABCD
:secret_access_key:                     asdfasdjghalskgjhsadkgjhaslkgjashgkls
:account_id:                            12321346546

# For west coast availability zone, before poolparty run: export EC2_URL=https://us-west-1.ec2.amazonaws.com 
:availability_zones:                    [ "us-west-1a" ]

:attributes:
  :chef:
    :chef_server:                       "http://chef.infochimps.com:4000"

:pools:
  :zaius:
    :common:
      :instance_os:                     chef-client
      :instance_backing:                instance
    :master:                            
      :disable_api_termination:         false
      :elastic_ip:                      184.72.52.22
      :instance_os:                     chef-server
      :instance_backing:                ebs
      :attributes:
        :node_name:                     chef.infochimps.com
    :slave:
    :bootstrap:
      :instance_os:                     lucid
