:access_key:                            1235125ABCD
:secret_access_key:                     asdfasdjghalskgjhsadkgjhaslkgjashgkls
:account_id:                            12321346546
:bootstrap_scripts_url_base:            http://github.com/infochimps/hadoop_cluster_chef/raw/master/config

# For west coast availability zone, before poolparty run: export EC2_URL=https://us-west-1.ec2.amazonaws.com 
:availability_zones:                    [ "us-east-1d" ]
:ec2_url:                               https://us-east-1.ec2.amazonaws.com
:aws_region:                            us-east-1
:instance_type:                         m1.small
:instance_os:                           lucid

:disable_api_termination:               false
:spot_price_fraction:                   ~
:boot_volume:                     
  :ebs_volume_size:                     15
  :ebs_delete_on_termination:           true

:attributes:
  :chef:
    :validation_key_file:               "~/.hadoop-ec2/keypairs/chef-validator.pem"
    :chef_server:                       "http://chef.infinitemonkeys.info:4000"
    :validation_client_name:            "chef-validator"

:pools:
  :chef:
    :server:
      :attributes:
        :node_name:                     kong.infinitemonkeys.info
      :disable_api_termination:         true
      :elastic_ip:                      204.236.225.50
      :instance_os:                     lucid
      :instance_backing:                ebs
      :boot_volume:                     
        :ebs_volume_size:               15
        :ebs_delete_on_termination:     false
    :client:
      :instance_os:                     chef-client

  :zaius:
    :common:
      # 0.4 will dance right near the average (us-east-1). 1.0 will almost never shut down.
      :spot_price_fraction:             1.0
      :instance_type:                   c1.medium
      # :instance_type:                 m1.small
      :instance_os:                     chef-client
      :instance_backing:                instance
    :master:                            
      :elastic_ip:                      204.236.225.16
    :slave:                             
    :bootstrap:
      :instance_os:                     lucid
      :instance_backing:                instance
