#
# Copy this file to ~/.hadoop-ec2/poolparty.yaml
#

#
# AWS Credentials
#
# Set with environment variables, or uncomment and add your values
# 
# :access_key:                          1235125ABCD
# :secret_access_key:                   asdfasdjghalskgjhsadkgjhaslkgjashgkls
# :account_id:                          12321346546


#
# AWS instance settings  
# For west coast availability zone, before poolparty run: export EC2_URL=https://us-west-1.ec2.amazonaws.com
#
# :spot_price_fraction:                   ~
# :availability_zones:                    [ "us-east-1d" ]
# :instance_type:                         m1.small
# :instance_backing:                      instance
# :instance_os:                           lucid

# The user_data hash is passed to /etc/chef/client.rb via the EC2 user-data setting
:user_data:
  # hostname and port for chef server
  :chef_server:                         "http://chef.infochimps.com:4000"
  # Attributes for the node. Anything set here overrides all other node attributes
  :attributes:
    #

:pools:
  #
  # Small cluster.
  # * master node is Chef server, hadoop master and nfs-server.
  # * slaves use local drives for HDFS
  #
  :zaius:
    :common:
      # By default, use instance-backed AMI that runs chef-client at startup
      :instance_os:                     opscode-chef-client
      :instance_backing:                instance
      :instance_type:                   m1.small
    :chefmaster:
      # Use an EBS-backed AMI
      :instance_os:                     infochimps-chef-server
      :instance_backing:                ebs
      # Make an elastic IP; use your DNS service (or http://dyndns.org) to point a hostname to it
      :elastic_ip:                      184.72.52.22
      # Chef client settings
      :user_data:
        :attributes:
          # enter the hostname for your chef server
          :node_name:                   chef.infochimps.com
    :master:
      # Make an elastic IP; use your DNS service (or http://dyndns.org) to point a hostname to it
      :elastic_ip:                      184.72.52.22
    :slave:
